import type { NextApiRequest, NextApiResponse } from "next";

export default function handler(req: NextApiRequest, res: NextApiResponse) {
    const data = [
        {
            id: "p1",
            name: "Seaside Villa",
            images: ["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85"],
            rating: 4.8,
            address: { city: "Tulum", country: "Mexico" },
            price: 350,
            tags: ["Beachfront", "Top Villa", "Self Checkin"],
        },
        {
            id: "p2",
            name: "Mountain Retreat",
            images: ["https://images.unsplash.com/photo-1501183638710-841dd1904471"],
            rating: 4.7,
            address: { city: "Aspen", country: "USA" },
            price: 420,
            tags: ["Mountain View", "Pet Friendly"],
        },
        {
            id: "3",
            name: "Villa Ocean Breeze",
            address: {
                state: "Seminyak",
                city: "Bali",
                country: "Indonesia",
            },
            rating: 4.89,
            tags: ["Luxury Villa", "Pool", "Free Parking"],
            price: 3200,
            offers: {
                bed: "3",
                shower: "3",
                occupants: "4-6",
            },
            images: ["https://placehold.co/600x400"],
            discount: "",
        },
        {
            name: "Mountain Escape Chalet",
            address: {
                state: "Aspen",
                city: "Colorado",
                country: "USA",
            },
            rating: 4.7,
            tags: ["Mountain View", "Fireplace", "Self Checkin"],
            price: 1800,
            offers: {
                bed: "4",
                shower: "2",
                occupants: "5-7",
            },
            images: ["https://placehold.co/600x400"],
            discount: "30",
        },
        {
            name: "Cozy Desert Retreat",
            address: {
                state: "Palm Springs",
                city: "California",
                country: "USA",
            },
            rating: 4.92,
            tags: ["Desert View", "Pet Friendly", "Self Checkin"],
            price: 1500,
            offers: {
                bed: "2",
                shower: "1",
                occupants: "2-3",
            },
            images: ["https://placehold.co/600x400"],
            discount: "",
        },
        {
            name: "City Lights Penthouse",
            address: {
                state: "New York",
                city: "New York",
                country: "USA",
            },
            rating: 4.85,
            tags: ["City View", "Free WiFi", "24h Checkin"],
            price: 4500,
            offers: {
                bed: "2",
                shower: "2",
                occupants: "2-4",
            },
            images: ["https://placehold.co/600x400"],
            discount: "15",
        },
        {
            name: "Riverside Cabin",
            address: {
                state: "Queenstown",
                city: "Otago",
                country: "New Zealand",
            },
            rating: 4.77,
            tags: ["Riverside", "Private Dock", "Free Kayaks"],
            price: 2800,
            offers: {
                bed: "3",
                shower: "2",
                occupants: "4-6",
            },
            images: ["https://placehold.co/600x400"],
            discount: "20",
        },
        {
            name: "Modern Beachfront Villa",
            address: {
                state: "Sidemen",
                city: "Bali",
                country: "Indonesia",
            },
            rating: 4.95,
            tags: ["Beachfront", "Private Pool", "Chef Service"],
            price: 5000,
            offers: {
                bed: "5",
                shower: "4",
                occupants: "8-10",
            },
            images: ["https://placehold.co/600x400"],
            discount: "",
        },
        {
            name: "Lakeside Chalet",
            address: {
                state: "Banff",
                city: "Alberta",
                country: "Canada",
            },
            rating: 4.65,
            tags: ["Lakeside", "Mountain View", "Hiking Trails"],
            price: 2300,
            offers: {
                bed: "3",
                shower: "3",
                occupants: "4-5",
            },
            images: ["https://placehold.co/600x400"],
            discount: "10",
        },
        {
            name: "Tropical Garden Villa",
            address: {
                state: "Koh Samui",
                city: "Surat Thani",
                country: "Thailand",
            },
            rating: 4.8,
            tags: ["Garden", "Free Parking", "Self Checkin"],
            price: 2750,
            offers: {
                bed: "3",
                shower: "3",
                occupants: "5-6",
            },
            images: ["https://placehold.co/600x400"],
            discount: "25",
        },
        {
            name: "Urban Loft",
            address: {
                state: "Berlin",
                city: "Berlin",
                country: "Germany",
            },
            rating: 4.6,
            tags: ["City Center", "Free WiFi", "24h Checkin"],
            price: 2000,
            offers: {
                bed: "2",
                shower: "1",
                occupants: "2-3",
            },
            images: ["https://placehold.co/600x400"],
            discount: "",
        },
        {
            name: "Secluded Forest Cabin",
            address: {
                state: "Whistler",
                city: "British Columbia",
                country: "Canada",
            },
            rating: 4.72,
            tags: ["Secluded", "Hot Tub", "Self Checkin"],
            price: 2600,
            offers: {
                bed: "4",
                shower: "2",
                occupants: "5-7",
            },
            images: ["https://placehold.co/600x400"],
            discount: "40",
        },
        {
            name: "Cliffside Villa",
            address: {
                state: "Amalfi",
                city: "Salerno",
                country: "Italy",
            },
            rating: 4.93,
            tags: ["Cliffside", "Infinity Pool", "Sea View"],
            price: 6000,
            offers: {
                bed: "4",
                shower: "4",
                occupants: "6-8",
            },
            images: ["https://placehold.co/600x400"],
            discount: "50",
        },
        {
            name: "Coastal Escape Villa",
            address: {
                state: "Noosa",
                city: "Queensland",
                country: "Australia",
            },
            rating: 4.83,
            tags: ["Beachfront", "Pet Friendly", "Free Parking"],
            price: 3400,
            offers: {
                bed: "3",
                shower: "3",
                occupants: "4-6",
            },
            images: ["https://placehold.co/600x400"],
            discount: "",
        },
        {
            name: "Historical Villa",
            address: {
                state: "Florence",
                city: "Tuscany",
                country: "Italy",
            },
            rating: 4.67,
            tags: ["Historical", "Free Breakfast", "Self Checkin"],
            price: 2700,
            offers: {
                bed: "2",
                shower: "2",
                occupants: "2-4",
            },
            images: ["https://placehold.co/600x400"],
            discount: "35",
        },
        {
            name: "Downtown Apartment",
            address: {
                state: "Tokyo",
                city: "Tokyo",
                country: "Japan",
            },
            rating: 4.81,
            tags: ["City Center", "Free WiFi", "Public Transport"],
            price: 2200,
            offers: {
                bed: "1",
                shower: "1",
                occupants: "2",
            },
            images: ["https://placehold.co/600x400"],
            discount: "",
        },
        {
            name: "Luxury Safari Lodge",
            address: {
                state: "Serengeti",
                city: "Mara",
                country: "Tanzania",
            },
            rating: 4.97,
            tags: ["Safari", "Guided Tours", "Free Breakfast"],
            price: 4500,
            offers: {
                bed: "4",
                shower: "4",
                occupants: "6-8",
            },
            images: ["https://placehold.co/600x400"],
            discount: "20",
        },
        {
            name: "Countryside Cottage",
            address: {
                state: "Cotswolds",
                city: "Gloucestershire",
                country: "UK",
            },
            rating: 4.58,
            tags: ["Countryside", "Fireplace", "Self Checkin"],
            price: 1800,
            offers: {
                bed: "2",
                shower: "1",
                occupants: "2-4",
            },
            images: ["https://placehold.co/600x400"],
            discount: "25",
        },
        {
            name: "Riverfront Mansion",
            address: {
                state: "Paris",
                city: "Île-de-France",
                country: "France",
            },
            rating: 4.86,
            tags: ["Riverfront", "Private Garden", "Self Checkin"],
            price: 5000,
            offers: {
                bed: "4",
                shower: "3",
                occupants: "6-8",
            },
            images: ["https://placehold.co/600x400"],
            discount: "30",
        },
        {
            name: "Ski Chalet",
            address: {
                state: "Zermatt",
                city: "Valais",
                country: "Switzerland",
            },
            rating: 4.75,
            tags: ["Mountain View", "Ski Access", "Fireplace"],
            price: 3900,
            offers: {
                bed: "3",
                shower: "3",
                occupants: "4-5",
            },
            images: ["https://placehold.co/600x400"],
            discount: "",
        },
        {
            name: "Island Paradise Villa",
            address: {
                state: "Mahe",
                city: "Victoria",
                country: "Seychelles",
            },
            rating: 4.98,
            tags: ["Beachfront", "Private Pool", "Chef Service"],
            price: 6500,
            offers: {
                bed: "5",
                shower: "5",
                occupants: "8-10",
            },
            images: ["https://placehold.co/600x400"],
            discount: "60",
        },
        {
            name: "Clifftop Retreat",
            address: {
                state: "Cape Town",
                city: "Western Cape",
                country: "South Africa",
            },
            rating: 4.78,
            tags: ["Ocean View", "Private Pool", "Self Checkin"],
            price: 4100,
            offers: {
                bed: "3",
                shower: "3",
                occupants: "4-5",
            },
            images: ["https://placehold.co/600x400"],
            discount: "",
        },
    ];
    res.status(200).json(data);
}
